camera1:
  camera:
    ros__parameters:
      device_type: 'd435i'
      serial_no: ''
      usb_port_id: ''
      rosbag_filename: ''
      initial_reset: true

      filters: ''
      enable_sync: false

      enable_color: true
      color_width: 640
      color_height: 480
      color_fps: 30.0
      color_frame_id: camera_color_frame
      color_optical_frame_id: camera_color_optical_frame
      color_qos: DEFAULT

      enable_depth: false
      depth_width: 1280
      depth_height: 720
      depth_fps: 15.0
      depth_frame_id: camera_depth_frame
      depth_optical_frame_id: camera_depth_optical_frame

      enable_accel: false
      accel_fps: 0.0
      accel_frame_id: camera_accel_frame
      accel_optical_frame_id: camera_accel_optical_frame

      enable_gyro: false
      gyro_fps: 0.0
      gyro_frame_id: camera_gyro_frame
      gyro_optical_frame_id: camera_gyro_optical_frame

      enable_pose: false
      # pose_fps: 0.0
      # pose_frame_id: camera_pose_frame
      # pose_optical_frame_id: camera_pose_optical_frame

      enable_infra: false
      # infra_width: 1280
      # infra_height: 720
      # infra_fps: 15.0
      # infra_frame_id: camera_infra_frame
      # infra_optical_frame_id: camera_infra_optical_frame

      enable_infra1: false
      # infra1_frame_id: camera_infra1_frame
      # infra1_optical_frame_id: camera_infra1_optical_frame

      enable_infra2: false
      # infra2_frame_id: camera_infra2_frame
      # infra2_optical_frame_id: camera_infra2_optical_frame

      # pointcloud_texture_stream: RS2_STREAM_COLOR
      # pointcloud_texture_index: 0
      # allow_no_texture_points: false

      base_frame_id: camera_link
      odom_frame_id: odom

      align_depth: false
      # aligned_depth_to_color_frame_id: camera_aligned_depth_to_color_frame
      # aligned_depth_to_infra_frame_id: camera_aligned_depth_to_infra_frame
      # aligned_depth_to_infra1_frame_id: camera_aligned_depth_to_infra1_frame

      unite_imu_method: 'linear_interpolation'

      clip_distance: -1.0

      linear_accel_cov: 0.01
      angular_velocity_cov: 0.01
      hold_back_imu_for_frames: false

      publish_tf: true
      tf_publish_rate: 0.0
      publish_odom_tf: true

      motion_module:
        enable_motion_correction: true
        frames_queue_size: 16
        global_time_enabled: true
